version: '2'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      POSTGRES_DB: 'recordings'
      POSTGRES_USER: 'indio'
      POSTGRES_PASSWORD: 'Jandepora19882!'
    ports:
      - "5432:5432"
    volumes:
      - recordings-datavolume:/var/lib/postgres
volumes:
  recordings-datavolume:
