version: '2'
services:
  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'Jandepora19882!'
      MYSQL_USER: 'indio'
      MYSQL_PASS: 'Jandepora19882!'
    volumes:
      - recordings-datavolume:/var/lib/mysql
volumes:
  recordings-datavolume:
